### ISSUE TITLE
Add `DRAFT` view of the label

### ISSUE THREAD

**Issue by mewtaylor** [Data-Nutrition-Project/dnp-website#132]
This should be where someone can see a draft of their label after submitting a questionnaire. Needs design of the big bold alert that says it's a draft.

**Comment by kaschm** [comment]
A bit more info: 

- Someone should be able to see a DRAFT of their label before submission from the Label Maker 
- In this view, the Label has a watermark across the back that says DRAFT or PREVIEW or something to that effect 
- Label does not appear in the list of Labels on the website at this stage

**Comment by mewtaylor** [comment]
Finished in #146
