### ISSUE TITLE
Updates to site in advance of Label v3! 

### ISSUE THREAD

**Issue by kaschm** [Data-Nutrition-Project/dnp-website#135]
Website updates, captured from convo with Matt 1/27:

Infrastructure:
- Move away from github pages to heroku 

Nav Bar:
- About [sub-nav: Mission, Problem, Research, all are anchor links to same page]
- Label [point to label maker]
- Workshops (anchor link) 
- Team (anchor link) 
- FAQ (anchor link)
- Contact (anchor link) 

Label button on hero: go to new labelmaker landing

The Tool:
- Update image to new risks section
- One button only, "Build a Label", goes to label maker landing

FOR NOW: no new content

**Comment by mewtaylor** [comment]
Implemented in #148
