### ISSUE TITLE
Configure travis for dnp-website for autonomous testing

### ISSUE THREAD

**Issue by mewtaylor** [Data-Nutrition-Project/dnp-website#2]
Question to consider: can deployment to gh-pages be made dependent on travis testing?

**Comment by kem247** [comment]
I believe that since CI is to help with merging frequent small code changes that we can use it with gh-pages. 

Whenever I make a PR it will show the Travis results to see if there's any errors. I would need to give the yml file a github token

**Comment by mewtaylor** [comment]
@kem247 ah yeah was just seeing that when I was looking at #3 (see: https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/, is that what you were looking at too?).

**Comment by kem247** [comment]
Yes I was referring to that, I added the travis file into my pull request. Let me know I am making my pull requests okay. I believe I need permission to use Travis CI 
<img width="1138" alt="Screen Shot 2020-04-22 at 7 31 58 PM" src="https://user-images.githubusercontent.com/28695338/80043531-fe6eea80-84cf-11ea-98e9-c902efa7d53f.png">
