### ISSUE TITLE
`img` styling using tag rather than className

### ISSUE THREAD

**Issue by mewtaylor** [Data-Nutrition-Project/dnp-website#23]
In the `LabelTitle` module, there is some styling for an `img` tag that does not come with a specific class. Because of how css modules is styling, this means every img tag on the page is getting these values, rather than the one just for the `LabelTitle` component, which is causing conflicts with the header icon image.

**Comment by kem247** [comment]
Okay thank you, I'll keep that in mind for the future.

**Comment by mewtaylor** [comment]
Fixed in #28
