### ISSUE TITLE
`LabelTitle` using `header` tag

### ISSUE THREAD

**Issue by mewtaylor** [Data-Nutrition-Project/dnp-website#24]
@kem247 sorry I didn't catch this in review! The `header` tag should mainly be used for the page header, which in our case is the nav, as defined in the Layout and Header components. So, the code in LabelTitle which says:

```html
<header>Data Nutrition Label</header>
```
should be changes to an h1, or h2 tag. And the css for this should not go directly on the tag, but rather have a class name. The only time that tags should get stylings is in global declarations, which for us will be in the `layout` component.

**Comment by kem247** [comment]
Okay, I will quickly change that!

**Comment by mewtaylor** [comment]
closed by #26
