### ISSUE TITLE
Add description text for LabelMenu sections

### ISSUE THREAD

**Issue by mewtaylor** [Data-Nutrition-Project/dnp-website#31]
For the label menu, we need a description of what each section contains, which will go below the section headers. This means a description for:
- Use Cases & Alerts
- Overview Section
- Maintenance Section

**Comment by kaschm** [comment]
Yes! Here we go: 

USE CASES & ALERTS
Relevant alerts for data practitioners who intent to use this dataset for specific use cases (types of analyses).

OVERVIEW
Overview information about the dataset including Description, Provenance, Composition, and Collection. 

MAINTENANCE
Information about the ongoing management of the dataset, such as how the data will be maintained, updated, and the best contact for further inquiries.

**Comment by mewtaylor** [comment]
@kaschm I think this is no longer relevant with the new menu design, right? Or do we want these descriptions at the top of the label section when it's seen for context?

**Comment by mewtaylor** [comment]
Closing as no lonoger relevant
