### ISSUE TITLE
On Overview page, link 'Top Use Cases' to Use Case / Alert Page 

### ISSUE THREAD

**Issue by kaschm** [Data-Nutrition-Project/dnp-website#53]
On the 'Overview' Page, link from the 'Top Use Cases' to the 'Use Case/ Alert' view. If possible, link directly from each use case to that particular view. If not, link the 'Top Use Cases' text itself to the view (maybe use little link box next to title).

**Comment by mewtaylor** [comment]
Closing as no longer in designs
